pipeline {
    agent { 
        kubernetes {
               
            yaml '''
apiVersion: v1
kind: Pod
metadata:
  name: kaniko-test
  namespace: jenkins
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    command: 
    - sleep
    args: 
    - infinity
    volumeMounts:
      - name: kaniko-secret
        mountPath: /kaniko/.docker
  volumes:
    - name: kaniko-secret
      secret:
        secretName: kaniko-test
        items:
          - key: .dockerconfigjson
            path: config.json
'''
        }

    }
    stages {
        stage('Main') {
           
            steps {
             withCredentials([string(credentialsId: 'awsaccountnum', variable: 'SECRET')]) { 
                container(name: 'kaniko') {
                sh '--dockerfile=go-test/Dockerfile'
                sh '--context=git://github.com/coldpaper2/jenkins-test.git'
                sh '"--destination=${awsaccountnum}.dkr.ecr.ap-northeast-2.amazonaws.com/jenkins-test:${BUILD_NUM}"]'
            }
		}
         }   
        }
    }
}
