pipeline {
    agent { 
        kubernetes {
               
            yaml '''
apiVersion: v1
kind: Pod
metadata:
  name: kaniko-test
  namespace: jenkins
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    ports:
    - containerPort: 50000
    command: 
    - sleep
    args: 
    - infinity
    volumeMounts:
      - name: kaniko-secret
        mountPath: /kaniko/.docker
  volumes:
    - name: kaniko-secret
      secret:
        secretName: kaniko-test
        items:
          - key: .dockerconfigjson
            path: config.json
'''
        }

    }
    stages {
        stage('Main') {
           
            steps {
             withCredentials([string(credentialsId: 'awsaccountnum', variable: 'SECRET')]) { 
                container(name: 'kaniko') {
                sh '--dockerfile=go-test/Dockerfile'
                sh '--context=git://github.com/coldpaper2/jenkins-k8s.git'
                sh '--destination=mhkim1560/jenkins-test:${BUILD_NUM}'
            }
		}
         }   
        }
    }
}
